# Generated by Django 4.2.19 on 2025-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_gen", "0003_alter_bingocard_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingocard",
            name="marked_numbers",
            field=models.JSONField(default=list),
        ),
    ]
